-- MySQL Script generated by MySQL Workbench
-- Tue May 21 11:08:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema InternshipDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema InternshipDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InternshipDB` DEFAULT CHARACTER SET utf8 ;
USE `InternshipDB` ;

-- -----------------------------------------------------
-- Table `InternshipDB`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InternshipDB`.`Posts` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NULL,
  `Adress` VARCHAR(100) NULL,
  `Description` TEXT NULL,
  `Duration` TIMESTAMP NULL,
  `Salary` SMALLINT UNSIGNED NULL,
  `Technologies` TEXT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InternshipDB`.`Interns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InternshipDB`.`Interns` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Age` SMALLINT UNSIGNED NOT NULL,
  `Mobile` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(80) NULL,
  `University` VARCHAR(100) NULL,
  `Faculty` VARCHAR(100) NULL,
  `CV` MEDIUMBLOB NULL,
  `Login` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `IdPosts` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  INDEX `IdPosts_idx` (`IdPosts` ASC),
  CONSTRAINT `IdPosts`
    FOREIGN KEY (`IdPosts`)
    REFERENCES `InternshipDB`.`Posts` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InternshipDB`.`Companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InternshipDB`.`Companies` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Adress` VARCHAR(100) NULL,
  `Mobile` VARCHAR(30) NULL,
  `Email` VARCHAR(60) NULL,
  `Description` TEXT NULL,
  `Login` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `IdPosts` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `idCompanies_UNIQUE` (`Id` ASC),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  INDEX `IdPosts_idx` (`IdPosts` ASC),
  CONSTRAINT `IdPosts`
    FOREIGN KEY (`IdPosts`)
    REFERENCES `InternshipDB`.`Posts` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InternshipDB`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InternshipDB`.`Admins` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
